name: Deploy python app

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "*.md"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        shell: powershell
        run: |
          "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" | Out-File -FilePath .env -Encoding UTF8
          "MONGO_URI=${{ secrets.MONGO_URI }}" | Out-File -FilePath .env -Append -Encoding UTF8
          "POSTING_LOG_LEVEL=INFO" | Out-File -FilePath .env -Append -Encoding UTF8

      - name: Run docker compose
        shell: powershell
        run: |
          docker compose down # remove any potential old containers
          docker compose up --build -d
