name: Deploy python app

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Copy over env
        run: |
          powershell.exe -Command '
            echo "" | Out-File -FilePath .env -Encoding UTF8 ; echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" | Out-File -FilePath .env -Append -Encoding UTF8 ; echo "MONGO_URI=${{ secrets.MONGO_URI }}" | Out-File -FilePath .env -Append -Encoding UTF8
          '

      - name: Run docker
        run: |
          powershell.exe -Command 'docker compose up --build -d'
